import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";



const montserrat = Montserrat({ subsets: ["latin"] , variable:"--font-mont"});

export const metadata = {
  title: "Nujat Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${montserrat.className} bg-light dark:bg-dark font-mont w-full min-h-screen`}>
      
        <Navbar/> 
        {children}</body>
    </html>
  );
}
